import { AppError, ValidationError } from "../utils/error.js"

function cw(controller) {
    return async (req, res, next) => {
        try {
            await controller(req, res, next);
        } catch (error) {
            next(error)
        }
    }
};

// * Middleware de gestion d'erreurs
function errorHandler(err, req, res, next) {
    console.error("üí• Erreur non g√©r√©e :", err);

    // * Si c'est une de nos erreurs personnalis√©es 404 ou 400 (sch√©mas)
    if (err instanceof AppError) {
    return res.status(err.statusCode).json({
        error: err.message,
        // * Si l'√©rreur vient du sch√©ma on ajoute les d√©tails au message 
        ...(err instanceof ValidationError && { details: err.details })
    });
    }
    // * Pour les erreurs non g√©r√©es
    res.status(500).json({ 
        error: "Une erreur inattendue est survenue, merci de r√©essayer plus tard."
        });
}

// * Middleware pour les routes non trouv√©es
function notFoundHandler(req, res) {
    res.status(404).json({
    error: "Route non trouv√©e"
    });

}

export { cw, errorHandler, notFoundHandler}